// <auto-generated />
using System;
using BeFit_REPO.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeFit_REPO.Migrations
{
    [DbContext(typeof(BeFitAppContext))]
    [Migration("20240204202248_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeFit_DATA.Concrete.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Category ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Category Name")
                        .HasColumnOrder(2);

                    b.HasKey("ID");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Vegetable"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Fruit"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Soft drink"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Alcohol"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Snack"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Dessert"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Salad"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Dairy"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Fish and seafood"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Fast food"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Meat or poultry"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Grain, bean and nuts"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Food ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("Calorie")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrate")
                        .HasColumnType("float");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Food Name")
                        .HasColumnOrder(2);

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("PortionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Food", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Calorie = 60.0,
                            Carbohydrate = 13.5,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Artichoke",
                            PortionType = "Unit",
                            Protein = 3.5
                        },
                        new
                        {
                            ID = 2,
                            Calorie = 25.0,
                            Carbohydrate = 3.7000000000000002,
                            CategoryID = 1,
                            Fat = 0.69999999999999996,
                            Name = "Arugula",
                            PortionType = "Gram",
                            Protein = 2.6000000000000001
                        },
                        new
                        {
                            ID = 3,
                            Calorie = 20.0,
                            Carbohydrate = 3.8999999999999999,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Asparagus",
                            PortionType = "Unit",
                            Protein = 2.2000000000000002
                        },
                        new
                        {
                            ID = 4,
                            Calorie = 24.0,
                            Carbohydrate = 5.7000000000000002,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Aubergine",
                            PortionType = "Unit",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 5,
                            Calorie = 43.0,
                            Carbohydrate = 9.5999999999999996,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Beetroot",
                            PortionType = "Unit",
                            Protein = 1.6000000000000001
                        },
                        new
                        {
                            ID = 6,
                            Calorie = 20.0,
                            Carbohydrate = 4.7000000000000002,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Bell pepper",
                            PortionType = "Unit",
                            Protein = 0.90000000000000002
                        },
                        new
                        {
                            ID = 7,
                            Calorie = 115.0,
                            Carbohydrate = 6.2999999999999998,
                            CategoryID = 1,
                            Fat = 10.699999999999999,
                            Name = "Black olives",
                            PortionType = "Unit",
                            Protein = 0.80000000000000004
                        },
                        new
                        {
                            ID = 8,
                            Calorie = 34.0,
                            Carbohydrate = 6.5999999999999996,
                            CategoryID = 1,
                            Fat = 0.40000000000000002,
                            Name = "Broccoli",
                            PortionType = "Gram",
                            Protein = 2.7999999999999998
                        },
                        new
                        {
                            ID = 9,
                            Calorie = 43.0,
                            Carbohydrate = 8.9000000000000004,
                            CategoryID = 1,
                            Fat = 0.29999999999999999,
                            Name = "Brussels sprouts",
                            PortionType = "Gram",
                            Protein = 3.3999999999999999
                        },
                        new
                        {
                            ID = 10,
                            Calorie = 25.0,
                            Carbohydrate = 5.7999999999999998,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Cabbage",
                            PortionType = "Floweret",
                            Protein = 1.3
                        },
                        new
                        {
                            ID = 11,
                            Calorie = 18.0,
                            Carbohydrate = 4.2999999999999998,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Capsicum",
                            PortionType = "Unit",
                            Protein = 0.90000000000000002
                        },
                        new
                        {
                            ID = 12,
                            Calorie = 41.0,
                            Carbohydrate = 9.5999999999999996,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Carrot",
                            PortionType = "Unit",
                            Protein = 0.90000000000000002
                        },
                        new
                        {
                            ID = 13,
                            Calorie = 25.0,
                            Carbohydrate = 5.0,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Cauliflower",
                            PortionType = "Floweret",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 14,
                            Calorie = 14.0,
                            Carbohydrate = 3.0,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Celery",
                            PortionType = "Plate",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 15,
                            Calorie = 3.0,
                            Carbohydrate = 0.69999999999999996,
                            CategoryID = 1,
                            Fat = 0.0,
                            Name = "Cherry tomato",
                            PortionType = "Unit",
                            Protein = 0.20000000000000001
                        },
                        new
                        {
                            ID = 16,
                            Calorie = 12.0,
                            Carbohydrate = 2.2000000000000002,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Chinese cabbage",
                            PortionType = "Floweret",
                            Protein = 1.2
                        },
                        new
                        {
                            ID = 17,
                            Calorie = 32.0,
                            Carbohydrate = 5.9000000000000004,
                            CategoryID = 1,
                            Fat = 0.59999999999999998,
                            Name = "Collard greens",
                            PortionType = "Gram",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 18,
                            Calorie = 123.0,
                            Carbohydrate = 25.699999999999999,
                            CategoryID = 1,
                            Fat = 1.5,
                            Name = "Corn",
                            PortionType = "Unit",
                            Protein = 4.7000000000000002
                        },
                        new
                        {
                            ID = 19,
                            Calorie = 17.0,
                            Carbohydrate = 3.1000000000000001,
                            CategoryID = 1,
                            Fat = 0.29999999999999999,
                            Name = "Courgette",
                            PortionType = "Gram",
                            Protein = 1.2
                        },
                        new
                        {
                            ID = 20,
                            Calorie = 16.0,
                            Carbohydrate = 3.6000000000000001,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Cucumber",
                            PortionType = "Unit",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 21,
                            Calorie = 336.0,
                            Carbohydrate = 1.2,
                            CategoryID = 11,
                            Fat = 30.0,
                            Name = "Salami",
                            PortionType = "Gram",
                            Protein = 14.0
                        },
                        new
                        {
                            ID = 22,
                            Calorie = 17.0,
                            Carbohydrate = 3.3999999999999999,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Endive",
                            PortionType = "Gram",
                            Protein = 1.3
                        },
                        new
                        {
                            ID = 23,
                            Calorie = 32.0,
                            Carbohydrate = 7.2999999999999998,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Fennel",
                            PortionType = "Gram",
                            Protein = 1.2
                        },
                        new
                        {
                            ID = 24,
                            Calorie = 4.0,
                            Carbohydrate = 1.0,
                            CategoryID = 1,
                            Fat = 0.0,
                            Name = "Garlic",
                            PortionType = "Unit",
                            Protein = 0.20000000000000001
                        },
                        new
                        {
                            ID = 25,
                            Calorie = 9.0,
                            Carbohydrate = 2.1000000000000001,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Gherkin",
                            PortionType = "Unit",
                            Protein = 0.40000000000000002
                        },
                        new
                        {
                            ID = 26,
                            Calorie = 108.0,
                            Carbohydrate = 27.0,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Gourd",
                            PortionType = "Unit",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 27,
                            Calorie = 32.0,
                            Carbohydrate = 7.0999999999999996,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Green beans",
                            PortionType = "Gram",
                            Protein = 1.8
                        },
                        new
                        {
                            ID = 28,
                            Calorie = 2.0,
                            Carbohydrate = 0.29999999999999999,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Green olives",
                            PortionType = "Unit",
                            Protein = 0.20000000000000001
                        },
                        new
                        {
                            ID = 29,
                            Calorie = 5.0,
                            Carbohydrate = 1.3,
                            CategoryID = 1,
                            Fat = 0.0,
                            Name = "Green onion",
                            PortionType = "Unit",
                            Protein = 0.29999999999999999
                        },
                        new
                        {
                            ID = 30,
                            Calorie = 7.0,
                            Carbohydrate = 1.7,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Horseradish",
                            PortionType = "Gram",
                            Protein = 0.20000000000000001
                        },
                        new
                        {
                            ID = 31,
                            Calorie = 43.0,
                            Carbohydrate = 8.8000000000000007,
                            CategoryID = 1,
                            Fat = 0.90000000000000002,
                            Name = "Kale",
                            PortionType = "Gram",
                            Protein = 4.2999999999999998
                        },
                        new
                        {
                            ID = 32,
                            Calorie = 54.0,
                            Carbohydrate = 12.6,
                            CategoryID = 1,
                            Fat = 0.29999999999999999,
                            Name = "Leek",
                            PortionType = "Unit",
                            Protein = 1.5
                        },
                        new
                        {
                            ID = 33,
                            Calorie = 109.0,
                            Carbohydrate = 20.100000000000001,
                            CategoryID = 1,
                            Fat = 2.2000000000000002,
                            Name = "Lettuce",
                            PortionType = "Unit",
                            Protein = 6.9000000000000004
                        },
                        new
                        {
                            ID = 34,
                            Calorie = 1.0,
                            Carbohydrate = 0.20000000000000001,
                            CategoryID = 1,
                            Fat = 0.0,
                            Name = "Mushrooms",
                            PortionType = "Unit",
                            Protein = 0.10000000000000001
                        },
                        new
                        {
                            ID = 35,
                            Calorie = 28.0,
                            Carbohydrate = 4.7000000000000002,
                            CategoryID = 1,
                            Fat = 0.40000000000000002,
                            Name = "Mustard greens",
                            PortionType = "Gram",
                            Protein = 2.8999999999999999
                        },
                        new
                        {
                            ID = 36,
                            Calorie = 33.0,
                            Carbohydrate = 7.5,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Okra",
                            PortionType = "Gram",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 37,
                            Calorie = 300.0,
                            Carbohydrate = 1.0,
                            CategoryID = 11,
                            Fat = 26.0,
                            Name = "Sausage",
                            PortionType = "Gram",
                            Protein = 14.0
                        },
                        new
                        {
                            ID = 38,
                            Calorie = 34.0,
                            Carbohydrate = 7.9000000000000004,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Onion",
                            PortionType = "Unit",
                            Protein = 1.1000000000000001
                        },
                        new
                        {
                            ID = 39,
                            Calorie = 128.0,
                            Carbohydrate = 30.199999999999999,
                            CategoryID = 1,
                            Fat = 0.59999999999999998,
                            Name = "Parsnips",
                            PortionType = "Unit",
                            Protein = 2.1000000000000001
                        },
                        new
                        {
                            ID = 40,
                            Calorie = 81.0,
                            Carbohydrate = 14.5,
                            CategoryID = 1,
                            Fat = 0.40000000000000002,
                            Name = "Peas",
                            PortionType = "Gram",
                            Protein = 5.4000000000000004
                        },
                        new
                        {
                            ID = 41,
                            Calorie = 29.0,
                            Carbohydrate = 0.10000000000000001,
                            CategoryID = 11,
                            Fat = 2.0,
                            Name = "Bacon",
                            PortionType = "Slice",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 42,
                            Calorie = 164.0,
                            Carbohydrate = 37.0,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Potato",
                            PortionType = "Unit",
                            Protein = 4.2999999999999998
                        },
                        new
                        {
                            ID = 43,
                            Calorie = 51.0,
                            Carbohydrate = 12.0,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Pumpkin",
                            PortionType = "Unit",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 44,
                            Calorie = 15.0,
                            Carbohydrate = 3.3999999999999999,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Radishes",
                            PortionType = "Unit",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 45,
                            Calorie = 260.0,
                            Carbohydrate = 62.0,
                            CategoryID = 1,
                            Fat = 1.5,
                            Name = "Red cabbage",
                            PortionType = "Unit",
                            Protein = 12.0
                        },
                        new
                        {
                            ID = 46,
                            Calorie = 147.0,
                            Carbohydrate = 35.0,
                            CategoryID = 1,
                            Fat = 0.5,
                            Name = "Rutabaga",
                            PortionType = "Unit",
                            Protein = 4.0999999999999996
                        },
                        new
                        {
                            ID = 47,
                            Calorie = 18.0,
                            Carbohydrate = 4.2000000000000002,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Shallots",
                            PortionType = "Unit",
                            Protein = 0.80000000000000004
                        },
                        new
                        {
                            ID = 48,
                            Calorie = 130.0,
                            Carbohydrate = 31.0,
                            CategoryID = 1,
                            Fat = 1.3999999999999999,
                            Name = "Squash",
                            PortionType = "Unit",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 49,
                            Calorie = 112.0,
                            Carbohydrate = 26.0,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Sweet potato",
                            PortionType = "Unit",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 50,
                            Calorie = 20.0,
                            Carbohydrate = 4.7000000000000002,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Tomato",
                            PortionType = "Unit",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 51,
                            Calorie = 34.0,
                            Carbohydrate = 7.9000000000000004,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Turnip",
                            PortionType = "Unit",
                            Protein = 1.1000000000000001
                        },
                        new
                        {
                            ID = 52,
                            Calorie = 95.0,
                            Carbohydrate = 25.100000000000001,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Apple",
                            PortionType = "Unit",
                            Protein = 0.5
                        },
                        new
                        {
                            ID = 53,
                            Calorie = 17.0,
                            Carbohydrate = 3.8999999999999999,
                            CategoryID = 2,
                            Fat = 0.10000000000000001,
                            Name = "Apricot",
                            PortionType = "Unit",
                            Protein = 0.5
                        },
                        new
                        {
                            ID = 54,
                            Calorie = 240.0,
                            Carbohydrate = 12.800000000000001,
                            CategoryID = 2,
                            Fat = 22.0,
                            Name = "Avocado",
                            PortionType = "Unit",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 55,
                            Calorie = 111.0,
                            Carbohydrate = 28.800000000000001,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Banana",
                            PortionType = "Unit",
                            Protein = 1.3
                        },
                        new
                        {
                            ID = 56,
                            Calorie = 43.0,
                            Carbohydrate = 9.8000000000000007,
                            CategoryID = 2,
                            Fat = 0.5,
                            Name = "Blackberries",
                            PortionType = "Gram",
                            Protein = 1.3999999999999999
                        },
                        new
                        {
                            ID = 57,
                            Calorie = 70.0,
                            Carbohydrate = 16.199999999999999,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Blood oranges",
                            PortionType = "Unit",
                            Protein = 1.3
                        },
                        new
                        {
                            ID = 58,
                            Calorie = 84.0,
                            Carbohydrate = 21.399999999999999,
                            CategoryID = 2,
                            Fat = 0.5,
                            Name = "Blueberries",
                            PortionType = "Gram",
                            Protein = 1.1000000000000001
                        },
                        new
                        {
                            ID = 59,
                            Calorie = 34.0,
                            Carbohydrate = 8.1999999999999993,
                            CategoryID = 2,
                            Fat = 0.20000000000000001,
                            Name = "Cantaloupe",
                            PortionType = "Gram",
                            Protein = 0.80000000000000004
                        },
                        new
                        {
                            ID = 60,
                            Calorie = 4.0,
                            Carbohydrate = 1.0,
                            CategoryID = 2,
                            Fat = 0.0,
                            Name = "Cherries",
                            PortionType = "Unit",
                            Protein = 0.10000000000000001
                        },
                        new
                        {
                            ID = 61,
                            Calorie = 46.0,
                            Carbohydrate = 12.199999999999999,
                            CategoryID = 2,
                            Fat = 0.10000000000000001,
                            Name = "Cranberries",
                            PortionType = "Gram",
                            Protein = 0.40000000000000002
                        },
                        new
                        {
                            ID = 62,
                            Calorie = 20.0,
                            Carbohydrate = 5.2999999999999998,
                            CategoryID = 2,
                            Fat = 0.0,
                            Name = "Dates",
                            PortionType = "Unit",
                            Protein = 0.20000000000000001
                        },
                        new
                        {
                            ID = 63,
                            Calorie = 37.0,
                            Carbohydrate = 9.5999999999999996,
                            CategoryID = 2,
                            Fat = 0.20000000000000001,
                            Name = "Figs",
                            PortionType = "Unit",
                            Protein = 0.40000000000000002
                        },
                        new
                        {
                            ID = 64,
                            Calorie = 125.0,
                            Carbohydrate = 30.5,
                            CategoryID = 7,
                            Fat = 0.5,
                            Name = "Fruit salad",
                            PortionType = "Bowl",
                            Protein = 2.5
                        },
                        new
                        {
                            ID = 65,
                            Calorie = 67.0,
                            Carbohydrate = 17.300000000000001,
                            CategoryID = 2,
                            Fat = 0.40000000000000002,
                            Name = "Grapes",
                            PortionType = "Gram",
                            Protein = 0.59999999999999998
                        },
                        new
                        {
                            ID = 66,
                            Calorie = 112.0,
                            Carbohydrate = 26.300000000000001,
                            CategoryID = 2,
                            Fat = 0.5,
                            Name = "Kiwi",
                            PortionType = "Unit",
                            Protein = 2.1000000000000001
                        },
                        new
                        {
                            ID = 67,
                            Calorie = 17.0,
                            Carbohydrate = 5.4000000000000004,
                            CategoryID = 2,
                            Fat = 0.20000000000000001,
                            Name = "Lemon",
                            PortionType = "Unit",
                            Protein = 0.59999999999999998
                        },
                        new
                        {
                            ID = 68,
                            Calorie = 20.0,
                            Carbohydrate = 6.9000000000000004,
                            CategoryID = 2,
                            Fat = 0.10000000000000001,
                            Name = "Lime",
                            PortionType = "Unit",
                            Protein = 0.5
                        },
                        new
                        {
                            ID = 69,
                            Calorie = 7.0,
                            Carbohydrate = 1.7,
                            CategoryID = 2,
                            Fat = 0.0,
                            Name = "Lychees",
                            PortionType = "Unit",
                            Protein = 0.10000000000000001
                        },
                        new
                        {
                            ID = 70,
                            Calorie = 47.0,
                            Carbohydrate = 11.699999999999999,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Mandarin oranges",
                            PortionType = "Unit",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 71,
                            Calorie = 202.0,
                            Carbohydrate = 50.299999999999997,
                            CategoryID = 2,
                            Fat = 1.3,
                            Name = "Mango",
                            PortionType = "Unit",
                            Protein = 2.7999999999999998
                        },
                        new
                        {
                            ID = 72,
                            Calorie = 66.0,
                            Carbohydrate = 15.800000000000001,
                            CategoryID = 2,
                            Fat = 0.40000000000000002,
                            Name = "Nectarine",
                            PortionType = "Unit",
                            Protein = 1.6000000000000001
                        },
                        new
                        {
                            ID = 73,
                            Calorie = 62.0,
                            Carbohydrate = 15.5,
                            CategoryID = 2,
                            Fat = 0.20000000000000001,
                            Name = "Orange",
                            PortionType = "Unit",
                            Protein = 1.2
                        },
                        new
                        {
                            ID = 74,
                            Calorie = 215.0,
                            Carbohydrate = 55.299999999999997,
                            CategoryID = 2,
                            Fat = 1.3,
                            Name = "Papaya",
                            PortionType = "Unit",
                            Protein = 2.5
                        },
                        new
                        {
                            ID = 75,
                            Calorie = 17.0,
                            Carbohydrate = 4.2000000000000002,
                            CategoryID = 2,
                            Fat = 0.10000000000000001,
                            Name = "Passion fruit",
                            PortionType = "Unit",
                            Protein = 0.40000000000000002
                        },
                        new
                        {
                            ID = 76,
                            Calorie = 59.0,
                            Carbohydrate = 14.800000000000001,
                            CategoryID = 2,
                            Fat = 0.40000000000000002,
                            Name = "Peach",
                            PortionType = "Unit",
                            Protein = 1.3999999999999999
                        },
                        new
                        {
                            ID = 77,
                            Calorie = 101.0,
                            Carbohydrate = 27.100000000000001,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Pear",
                            PortionType = "Unit",
                            Protein = 0.59999999999999998
                        },
                        new
                        {
                            ID = 78,
                            Calorie = 50.0,
                            Carbohydrate = 13.1,
                            CategoryID = 2,
                            Fat = 0.10000000000000001,
                            Name = "Pineapple",
                            PortionType = "Gram",
                            Protein = 0.5
                        },
                        new
                        {
                            ID = 79,
                            Calorie = 30.0,
                            Carbohydrate = 7.9000000000000004,
                            CategoryID = 2,
                            Fat = 0.20000000000000001,
                            Name = "Plum",
                            PortionType = "Unit",
                            Protein = 0.5
                        },
                        new
                        {
                            ID = 80,
                            Calorie = 234.0,
                            Carbohydrate = 58.799999999999997,
                            CategoryID = 2,
                            Fat = 3.2999999999999998,
                            Name = "Pomegranate",
                            PortionType = "Unit",
                            Protein = 4.7000000000000002
                        },
                        new
                        {
                            ID = 81,
                            Calorie = 300.0,
                            Carbohydrate = 79.200000000000003,
                            CategoryID = 5,
                            Fat = 0.5,
                            Name = "Raisins",
                            PortionType = "Gram",
                            Protein = 3.1000000000000001
                        },
                        new
                        {
                            ID = 82,
                            Calorie = 64.0,
                            Carbohydrate = 14.699999999999999,
                            CategoryID = 2,
                            Fat = 0.80000000000000004,
                            Name = "Raspberries",
                            PortionType = "Bowl",
                            Protein = 1.5
                        },
                        new
                        {
                            ID = 83,
                            Calorie = 49.0,
                            Carbohydrate = 11.699999999999999,
                            CategoryID = 2,
                            Fat = 0.5,
                            Name = "Strawberries",
                            PortionType = "Bowl",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 84,
                            Calorie = 47.0,
                            Carbohydrate = 11.699999999999999,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Tangerine",
                            PortionType = "Unit",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 85,
                            Calorie = 86.0,
                            Carbohydrate = 21.600000000000001,
                            CategoryID = 2,
                            Fat = 0.40000000000000002,
                            Name = "Watermelon",
                            PortionType = "Slice",
                            Protein = 1.7
                        },
                        new
                        {
                            ID = 86,
                            Calorie = 680.0,
                            Carbohydrate = 1.1000000000000001,
                            CategoryID = 8,
                            Fat = 61.5,
                            Name = "Bacon and eggs",
                            PortionType = "Serving",
                            Protein = 37.0
                        },
                        new
                        {
                            ID = 87,
                            Calorie = 150.0,
                            Carbohydrate = 22.100000000000001,
                            CategoryID = 12,
                            Fat = 0.5,
                            Name = "Baked beans",
                            PortionType = "Gram",
                            Protein = 9.5
                        },
                        new
                        {
                            ID = 88,
                            Calorie = 360.0,
                            Carbohydrate = 0.0,
                            CategoryID = 11,
                            Fat = 30.0,
                            Name = "Bbq ribs",
                            PortionType = "Unit",
                            Protein = 24.0
                        },
                        new
                        {
                            ID = 89,
                            Calorie = 186.0,
                            Carbohydrate = 11.4,
                            CategoryID = 11,
                            Fat = 7.2000000000000002,
                            Name = "Beef stew",
                            PortionType = "Bowl",
                            Protein = 18.300000000000001
                        },
                        new
                        {
                            ID = 90,
                            Calorie = 170.0,
                            Carbohydrate = 36.700000000000003,
                            CategoryID = 12,
                            Fat = 1.5,
                            Name = "Black rice",
                            PortionType = "Gram",
                            Protein = 3.5
                        },
                        new
                        {
                            ID = 91,
                            Calorie = 110.0,
                            Carbohydrate = 22.800000000000001,
                            CategoryID = 12,
                            Fat = 0.90000000000000002,
                            Name = "Brown rice",
                            PortionType = "Gram",
                            Protein = 2.6000000000000001
                        },
                        new
                        {
                            ID = 92,
                            Calorie = 326.0,
                            Carbohydrate = 31.300000000000001,
                            CategoryID = 10,
                            Fat = 16.0,
                            Name = "Burrito",
                            PortionType = "Unit",
                            Protein = 13.199999999999999
                        },
                        new
                        {
                            ID = 93,
                            Calorie = 33.0,
                            Carbohydrate = 6.0,
                            CategoryID = 9,
                            Fat = 0.69999999999999996,
                            Name = "California roll",
                            PortionType = "Unit",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 94,
                            Calorie = 309.0,
                            Carbohydrate = 12.0,
                            CategoryID = 7,
                            Fat = 20.5,
                            Name = "Chicken caesar salad",
                            PortionType = "Bowl",
                            Protein = 23.399999999999999
                        },
                        new
                        {
                            ID = 95,
                            Calorie = 290.0,
                            Carbohydrate = 8.4000000000000004,
                            CategoryID = 11,
                            Fat = 14.800000000000001,
                            Name = "Chicken marsala",
                            PortionType = "Serving",
                            Protein = 28.100000000000001
                        },
                        new
                        {
                            ID = 96,
                            Calorie = 350.0,
                            Carbohydrate = 13.0,
                            CategoryID = 11,
                            Fat = 22.0,
                            Name = "Chicken tikka masala",
                            PortionType = "Serving",
                            Protein = 25.0
                        },
                        new
                        {
                            ID = 97,
                            Calorie = 308.0,
                            Carbohydrate = 32.0,
                            CategoryID = 11,
                            Fat = 14.0,
                            Name = "Chimichanga",
                            PortionType = "Unit",
                            Protein = 15.0
                        },
                        new
                        {
                            ID = 98,
                            Calorie = 160.0,
                            Carbohydrate = 10.0,
                            CategoryID = 7,
                            Fat = 8.0,
                            Name = "Cobb salad",
                            PortionType = "Bowl",
                            Protein = 12.0
                        },
                        new
                        {
                            ID = 99,
                            Calorie = 180.0,
                            Carbohydrate = 18.0,
                            CategoryID = 10,
                            Fat = 10.0,
                            Name = "Corn dog",
                            PortionType = "Unit",
                            Protein = 7.0
                        },
                        new
                        {
                            ID = 100,
                            Calorie = 300.0,
                            Carbohydrate = 23.0,
                            CategoryID = 6,
                            Fat = 15.0,
                            Name = "Cottage pie",
                            PortionType = "Slice",
                            Protein = 17.0
                        },
                        new
                        {
                            ID = 101,
                            Calorie = 285.0,
                            Carbohydrate = 19.0,
                            CategoryID = 9,
                            Fat = 16.0,
                            Name = "Crab cake",
                            PortionType = "Unit",
                            Protein = 17.0
                        },
                        new
                        {
                            ID = 102,
                            Calorie = 321.0,
                            Carbohydrate = 33.0,
                            CategoryID = 5,
                            Fat = 19.0,
                            Name = "Creme brulee",
                            PortionType = "Unit",
                            Protein = 4.0
                        },
                        new
                        {
                            ID = 103,
                            Calorie = 406.0,
                            Carbohydrate = 45.0,
                            CategoryID = 11,
                            Fat = 23.0,
                            Name = "Croissant",
                            PortionType = "Unit",
                            Protein = 8.0
                        },
                        new
                        {
                            ID = 104,
                            Calorie = 131.0,
                            Carbohydrate = 20.0,
                            CategoryID = 10,
                            Fat = 5.0,
                            Name = "Cupcake",
                            PortionType = "Unit",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 105,
                            Calorie = 40.0,
                            Carbohydrate = 5.0,
                            CategoryID = 6,
                            Fat = 1.0,
                            Name = "Dumplings",
                            PortionType = "Piece",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 106,
                            Calorie = 220.0,
                            Carbohydrate = 23.0,
                            CategoryID = 5,
                            Fat = 14.0,
                            Name = "Eclair",
                            PortionType = "Unit",
                            Protein = 4.0
                        },
                        new
                        {
                            ID = 107,
                            Calorie = 68.0,
                            Carbohydrate = 0.59999999999999998,
                            CategoryID = 2,
                            Fat = 4.7999999999999998,
                            Name = "Egg",
                            PortionType = "Unit",
                            Protein = 5.5
                        },
                        new
                        {
                            ID = 108,
                            Calorie = 160.0,
                            Carbohydrate = 7.0,
                            CategoryID = 3,
                            Fat = 11.0,
                            Name = "Fried chicken",
                            PortionType = "Piece",
                            Protein = 10.0
                        },
                        new
                        {
                            ID = 109,
                            Calorie = 130.0,
                            Carbohydrate = 26.0,
                            CategoryID = 11,
                            Fat = 1.0,
                            Name = "Fried rice",
                            PortionType = "Gram",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 110,
                            Calorie = 118.0,
                            Carbohydrate = 19.0,
                            CategoryID = 7,
                            Fat = 4.0,
                            Name = "Granola bar",
                            PortionType = "Unit",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 111,
                            Calorie = 267.0,
                            Carbohydrate = 33.0,
                            CategoryID = 5,
                            Fat = 14.0,
                            Name = "Ice cream",
                            PortionType = "Unit",
                            Protein = 3.5
                        },
                        new
                        {
                            ID = 112,
                            Calorie = 265.0,
                            Carbohydrate = 38.0,
                            CategoryID = 11,
                            Fat = 12.0,
                            Name = "Muffin",
                            PortionType = "Unit",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 113,
                            Calorie = 71.0,
                            Carbohydrate = 12.0,
                            CategoryID = 7,
                            Fat = 1.5,
                            Name = "Oatmeal",
                            PortionType = "Gram",
                            Protein = 2.5
                        },
                        new
                        {
                            ID = 114,
                            Calorie = 159.0,
                            Carbohydrate = 29.0,
                            CategoryID = 9,
                            Fat = 3.5,
                            Name = "Pancake",
                            PortionType = "Unit",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 115,
                            Calorie = 285.0,
                            Carbohydrate = 36.0,
                            CategoryID = 10,
                            Fat = 10.0,
                            Name = "Pizza",
                            PortionType = "Slice",
                            Protein = 11.0
                        },
                        new
                        {
                            ID = 116,
                            Calorie = 365.0,
                            Carbohydrate = 77.0,
                            CategoryID = 8,
                            Fat = 4.0,
                            Name = "Popcorn",
                            PortionType = "Gram",
                            Protein = 9.0
                        },
                        new
                        {
                            ID = 117,
                            Calorie = 37.0,
                            Carbohydrate = 7.0,
                            CategoryID = 6,
                            Fat = 0.40000000000000002,
                            Name = "Sushi",
                            PortionType = "Piece",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 118,
                            Calorie = 206.0,
                            Carbohydrate = 0.0,
                            CategoryID = 3,
                            Fat = 13.4,
                            Name = "Salmon",
                            PortionType = "Gram",
                            Protein = 22.0
                        },
                        new
                        {
                            ID = 119,
                            Calorie = 144.0,
                            Carbohydrate = 0.0,
                            CategoryID = 3,
                            Fat = 1.0,
                            Name = "Tuna",
                            PortionType = "Gram",
                            Protein = 30.0
                        },
                        new
                        {
                            ID = 120,
                            Calorie = 85.0,
                            Carbohydrate = 0.0,
                            CategoryID = 3,
                            Fat = 0.90000000000000002,
                            Name = "Shrimp",
                            PortionType = "Gram",
                            Protein = 20.0
                        },
                        new
                        {
                            ID = 121,
                            Calorie = 250.0,
                            Carbohydrate = 0.0,
                            CategoryID = 3,
                            Fat = 17.0,
                            Name = "Lamb chop",
                            PortionType = "Gram",
                            Protein = 25.0
                        },
                        new
                        {
                            ID = 122,
                            Calorie = 86.0,
                            Carbohydrate = 19.0,
                            CategoryID = 4,
                            Fat = 1.2,
                            Name = "Sweet corn",
                            PortionType = "Gram",
                            Protein = 3.0
                        },
                        new
                        {
                            ID = 123,
                            Calorie = 17.0,
                            Carbohydrate = 3.1000000000000001,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Zucchini",
                            PortionType = "Gram",
                            Protein = 1.2
                        },
                        new
                        {
                            ID = 124,
                            Calorie = 23.0,
                            Carbohydrate = 3.6000000000000001,
                            CategoryID = 1,
                            Fat = 0.40000000000000002,
                            Name = "Spinach",
                            PortionType = "Gram",
                            Protein = 2.8999999999999999
                        },
                        new
                        {
                            ID = 125,
                            Calorie = 50.0,
                            Carbohydrate = 12.0,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Cherry",
                            PortionType = "Gram",
                            Protein = 1.0
                        },
                        new
                        {
                            ID = 126,
                            Calorie = 29.0,
                            Carbohydrate = 7.4000000000000004,
                            CategoryID = 2,
                            Fat = 0.20000000000000001,
                            Name = "Blueberry",
                            PortionType = "Gram",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 127,
                            Calorie = 32.0,
                            Carbohydrate = 7.7000000000000002,
                            CategoryID = 2,
                            Fat = 0.29999999999999999,
                            Name = "Strawberry",
                            PortionType = "Gram",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 128,
                            Calorie = 16.0,
                            Carbohydrate = 3.3999999999999999,
                            CategoryID = 1,
                            Fat = 0.10000000000000001,
                            Name = "Radish",
                            PortionType = "Gram",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            ID = 129,
                            Calorie = 43.0,
                            Carbohydrate = 9.5999999999999996,
                            CategoryID = 2,
                            Fat = 0.5,
                            Name = "Blackberry",
                            PortionType = "Gram",
                            Protein = 2.0
                        },
                        new
                        {
                            ID = 130,
                            Calorie = 52.0,
                            Carbohydrate = 11.9,
                            CategoryID = 2,
                            Fat = 0.69999999999999996,
                            Name = "Raspberry",
                            PortionType = "Gram",
                            Protein = 1.5
                        },
                        new
                        {
                            ID = 131,
                            Calorie = 25.0,
                            Carbohydrate = 6.0,
                            CategoryID = 1,
                            Fat = 0.20000000000000001,
                            Name = "Eggplant",
                            PortionType = "Gram",
                            Protein = 1.0
                        });
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("BodyMassIndex")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Last Name")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("First Name")
                        .HasColumnOrder(2);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(4);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnOrder(6);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrainingLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(5);

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.UserFood", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User Food ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("TotalCalorie")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.HasIndex("UserID");

                    b.ToTable("User Food", (string)null);
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.Food", b =>
                {
                    b.HasOne("BeFit_DATA.Concrete.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.UserFood", b =>
                {
                    b.HasOne("BeFit_DATA.Concrete.Food", "Food")
                        .WithMany("UserFoods")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeFit_DATA.Concrete.User", "User")
                        .WithMany("UserFoods")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.Food", b =>
                {
                    b.Navigation("UserFoods");
                });

            modelBuilder.Entity("BeFit_DATA.Concrete.User", b =>
                {
                    b.Navigation("UserFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
